export const FETCH_MOVIES = "FETCH_MOVIES";
export const ADD_TO_WATCHLIST = "UPDATE_WATCHLIST";
export const ADD_TO_WATCHED = "ADD_TO_WATCHED";
export const DELETE_FROM_WATCHLIST = "DELETE_FROM_WATCHLIST";
export const DELETE_FROM_WATCHED = "DELETE_FROM_WATCHED";
